languageCode: en-us
title: Hugo as CMS

defaultContentLanguage: en
enableMissingTranslationPlaceholders: false

disableKinds:
 - taxonomy
 - taxonomyTerm

languages:
  en:
    languageName: English
  de:
    languageName: German

params:
  debug: 0

imaging:
  resampleFilter: Lanczos
  quality: 95
  anchor: smart
